// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sample.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Person) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Person) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ListPersonRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPersonRequest) Reset()         { *m = ListPersonRequest{} }
func (m *ListPersonRequest) String() string { return proto.CompactTextString(m) }
func (*ListPersonRequest) ProtoMessage()    {}
func (*ListPersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{1}
}

func (m *ListPersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPersonRequest.Unmarshal(m, b)
}
func (m *ListPersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPersonRequest.Marshal(b, m, deterministic)
}
func (m *ListPersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPersonRequest.Merge(m, src)
}
func (m *ListPersonRequest) XXX_Size() int {
	return xxx_messageInfo_ListPersonRequest.Size(m)
}
func (m *ListPersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPersonRequest proto.InternalMessageInfo

type ListPersonResponse struct {
	Person               []*Person `protobuf:"bytes,1,rep,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListPersonResponse) Reset()         { *m = ListPersonResponse{} }
func (m *ListPersonResponse) String() string { return proto.CompactTextString(m) }
func (*ListPersonResponse) ProtoMessage()    {}
func (*ListPersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{2}
}

func (m *ListPersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPersonResponse.Unmarshal(m, b)
}
func (m *ListPersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPersonResponse.Marshal(b, m, deterministic)
}
func (m *ListPersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPersonResponse.Merge(m, src)
}
func (m *ListPersonResponse) XXX_Size() int {
	return xxx_messageInfo_ListPersonResponse.Size(m)
}
func (m *ListPersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPersonResponse proto.InternalMessageInfo

func (m *ListPersonResponse) GetPerson() []*Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "grpc/protos.Person")
	proto.RegisterType((*ListPersonRequest)(nil), "grpc/protos.ListPersonRequest")
	proto.RegisterType((*ListPersonResponse)(nil), "grpc/protos.ListPersonResponse")
}

func init() { proto.RegisterFile("sample.proto", fileDescriptor_2141552de9bf11d0) }

var fileDescriptor_2141552de9bf11d0 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x46, 0x95, 0xb4, 0x14, 0x18, 0xa0, 0x88, 0x81, 0x85, 0x89, 0x58, 0x54, 0x59, 0xa0, 0x8a,
	0x45, 0x22, 0xca, 0x0e, 0x71, 0x04, 0x16, 0xa8, 0x1c, 0x00, 0x19, 0x3c, 0xaa, 0x2c, 0xa5, 0x1e,
	0xe3, 0x71, 0xcb, 0x8e, 0x05, 0x57, 0xe0, 0x68, 0x5c, 0x81, 0x83, 0x20, 0xec, 0x06, 0x21, 0xc1,
	0x2a, 0xf9, 0xde, 0x9b, 0x1f, 0xdb, 0xb0, 0x2f, 0x7a, 0xe9, 0x3b, 0x6a, 0x7c, 0xe0, 0xc8, 0x38,
	0x4a, 0x1f, 0xa9, 0xce, 0x16, 0xcc, 0x8b, 0x8e, 0x5a, 0xed, 0x6d, 0xab, 0x9d, 0xe3, 0xa8, 0xa3,
	0x65, 0x27, 0xb9, 0xaa, 0x7e, 0x85, 0xd1, 0x1d, 0x05, 0x61, 0x87, 0x63, 0x28, 0xad, 0x51, 0xc5,
	0xa4, 0x98, 0xee, 0xce, 0x4b, 0x6b, 0x10, 0x61, 0xe8, 0xf4, 0x92, 0x54, 0x99, 0x48, 0xfa, 0x47,
	0x05, 0xdb, 0xda, 0x98, 0x40, 0x22, 0x6a, 0x90, 0x70, 0x1f, 0xb1, 0x82, 0x9d, 0x95, 0x50, 0x48,
	0x1d, 0xc3, 0xa4, 0x7e, 0xf2, 0xb7, 0xf3, 0x5a, 0xe4, 0x85, 0x83, 0x51, 0x5b, 0xd9, 0xf5, 0xb9,
	0x3e, 0x86, 0xa3, 0x5b, 0x2b, 0x31, 0x9f, 0x61, 0x4e, 0xcf, 0x2b, 0x92, 0x58, 0xdf, 0x00, 0xfe,
	0x86, 0xe2, 0xd9, 0x09, 0xe1, 0x39, 0x8c, 0x7c, 0x22, 0xaa, 0x98, 0x0c, 0xa6, 0x7b, 0xb3, 0x71,
	0xbe, 0x82, 0x34, 0x9b, 0xba, 0x8d, 0x9d, 0x79, 0x38, 0xc8, 0xe4, 0x9e, 0xc2, 0xda, 0x3e, 0x11,
	0x3e, 0x00, 0xe4, 0x71, 0xec, 0x3b, 0xc2, 0xd3, 0xbe, 0xed, 0xcf, 0xde, 0xaa, 0xfa, 0x4f, 0xe5,
	0xed, 0x75, 0xf5, 0xf6, 0xf1, 0xf9, 0x5e, 0x9e, 0xd4, 0x87, 0xed, 0xfa, 0xb2, 0xf5, 0x69, 0x54,
	0xd3, 0x59, 0x89, 0xd7, 0xc5, 0xc5, 0x63, 0x7e, 0xea, 0xab, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x5a, 0xac, 0x91, 0x7c, 0x81, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonServiceClient is the client API for PersonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonServiceClient interface {
	ListPeople(ctx context.Context, in *ListPersonRequest, opts ...grpc.CallOption) (*ListPersonResponse, error)
}

type personServiceClient struct {
	cc *grpc.ClientConn
}

func NewPersonServiceClient(cc *grpc.ClientConn) PersonServiceClient {
	return &personServiceClient{cc}
}

func (c *personServiceClient) ListPeople(ctx context.Context, in *ListPersonRequest, opts ...grpc.CallOption) (*ListPersonResponse, error) {
	out := new(ListPersonResponse)
	err := c.cc.Invoke(ctx, "/grpc/protos.PersonService/ListPeople", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonServiceServer is the server API for PersonService service.
type PersonServiceServer interface {
	ListPeople(context.Context, *ListPersonRequest) (*ListPersonResponse, error)
}

// UnimplementedPersonServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPersonServiceServer struct {
}

func (*UnimplementedPersonServiceServer) ListPeople(ctx context.Context, req *ListPersonRequest) (*ListPersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPeople not implemented")
}

func RegisterPersonServiceServer(s *grpc.Server, srv PersonServiceServer) {
	s.RegisterService(&_PersonService_serviceDesc, srv)
}

func _PersonService_ListPeople_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).ListPeople(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc/protos.PersonService/ListPeople",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).ListPeople(ctx, req.(*ListPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc/protos.PersonService",
	HandlerType: (*PersonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPeople",
			Handler:    _PersonService_ListPeople_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sample.proto",
}
